### ISSUE TITLE
Chatbot stream return if off by one job/command

### ISSUE THREAD

**Issue by hacfi** [vektorlab/multivac#11]
I was about to start developing something on my own (not a generic solution like yours) when I discovered this great project..love it! `slackcat` is also really cool!

I have one small issue though: The job’s/command’s output is off by one (running on EC2 Debian with docker-compose and the actions from the example:

```
hacfi: @devbot: echo stuff for me
hacfi: @devbot: count 5
devbotBOT: `[e5838702]Job initiated by hacfi`
devbotBOT: `[e5838702]stuff for me`
hacfi: @devbot: echo ping
devbotBOT: `[a8638796]Job initiated by hacfi`
devbotBOT: `[a8638796]{1..10} 5`
hacfi: @devbot: echo pong
devbotBOT: `[75cb72cc]Job initiated by hacfi`
devbotBOT: `[75cb72cc]ping`
```

When I check the web ui the logs match the command’s output. Also works fine if I create a job there.

Is this a known issue? How can I help to fix it?

Btw: http://multivac.vektor.nyc/config.html has a small typo at actions -> echo: `chatbot_strem` => `chatbot_stream`

**Comment by bcicen** [comment]
Glad you like it :)
I haven't come across this issue myself; does the issue persist after restarting mulitvac? I'll try to replicate it today.

Thanks for the heads up on the typo, fixed!

**Comment by hacfi** [comment]
@bcicen Yep, I could try running it on my macbook with ngrok. If you can’t reproduce it I can give you access to the host if you have time for that. Is there anything else I could try? Seems to be like a race condition or so..the log output looked fine.

**Comment by bcicen** [comment]
@hacfi I was able to reproduce the behavior. After a bit of digging, it turns out this was due to a race condition caused by running the incoming message loop in the same thread pool as the workers streaming the output back to Slack. Oddly, this hadn't been an issue when using earlier Python3 versions.

I've pushed a fix since; would you mind pulling the latest images and confirming the output is in sync?

**Comment by hacfi** [comment]
@bcicen Thank you so much..works like a charm!! Would have taken me ages to figure this out!

![You’re awesome!](https://media.giphy.com/media/JVdF14CQQH7gs/giphy.gif)
![Thank you](https://media.giphy.com/media/xIJLgO6rizUJi/giphy.gif)
